/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/invitations/{token}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Invitations Peek */
    get: operations['invitations_peek']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations/{token}/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Invitations Accept */
    post: operations['invitations_accept']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me Get */
    get: operations['me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Me Update */
    patch: operations['me_update']
    trace?: never
  }
  '/api/v1/me/onboarding': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Me Onboarding Update */
    patch: operations['me_onboarding_update']
    trace?: never
  }
  '/api/v1/workspaces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Workspaces List */
    get: operations['workspaces_list']
    put?: never
    /** Workspaces Create */
    post: operations['workspaces_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Workspaces Get */
    get: operations['workspaces_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Workspaces Update */
    patch: operations['workspaces_update']
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/invitations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Invitations List */
    get: operations['invitations_list']
    put?: never
    /** Invitations Create */
    post: operations['invitations_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/invitations/{invitation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Invitations Revoke */
    delete: operations['invitations_revoke']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Members List */
    get: operations['members_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Members Leave */
    delete: operations['members_leave']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Members Update */
    patch: operations['members_update']
    trace?: never
  }
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Live */
    get: operations['health_live']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Ready */
    get: operations['health_ready']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AcceptResult */
    AcceptResult: {
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /** Goals */
    Goals: {
      /**
       * Close Deals
       * @default false
       */
      close_deals?: boolean
      /**
       * Expand Network
       * @default false
       */
      expand_network?: boolean
      /**
       * Free Text
       * @default
       */
      free_text?: string
      /**
       * Strengthen
       * @default false
       */
      strengthen?: boolean
      /**
       * Track Roi
       * @default false
       */
      track_roi?: boolean
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InterestIn */
    InterestIn: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'professional' | 'personal'
      /** Value */
      value: string
    }
    /** InterestRead */
    InterestRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Value */
      value: string
    }
    /** InvitationCreate */
    InvitationCreate: {
      /** Email */
      email: string
      /** @default member */
      role?: components['schemas']['WorkspaceRole']
    }
    /** InvitationPeek */
    InvitationPeek: {
      /** Accepted */
      accepted: boolean
      /** Email */
      email: string
      /** Expired */
      expired: boolean
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Inviter Name */
      inviter_name: string
      role: components['schemas']['WorkspaceRole']
      /** Workspace Name */
      workspace_name: string
    }
    /** InvitationRead */
    InvitationRead: {
      /** Accepted At */
      accepted_at: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Email */
      email: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Invited By
       * Format: uuid
       */
      invited_by: string
      role: components['schemas']['WorkspaceRole']
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /** MeRead */
    MeRead: {
      /** Interests */
      interests: components['schemas']['InterestRead'][]
      /** Memberships */
      memberships: components['schemas']['MembershipRead'][]
      profile: components['schemas']['ProfileRead']
    }
    /** MeUpdate */
    MeUpdate: {
      /** Default Workspace Id */
      default_workspace_id?: string | null
      /** Full Name */
      full_name?: string | null
      goals?: components['schemas']['Goals'] | null
      /** Interests */
      interests?: components['schemas']['InterestIn'][] | null
      /** Role Title */
      role_title?: string | null
      /** Timezone */
      timezone?: string | null
    }
    /** MemberRead */
    MemberRead: {
      /** Avatar Path */
      avatar_path: string | null
      /** Departed At */
      departed_at: string | null
      /** Email */
      email: string
      /** Full Name */
      full_name: string
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
      role: components['schemas']['WorkspaceRole']
      /** Role Title */
      role_title: string | null
      status: components['schemas']['MembershipStatus']
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /** MemberUpdate */
    MemberUpdate: {
      role?: components['schemas']['WorkspaceRole'] | null
      status?: components['schemas']['MembershipStatus'] | null
    }
    /** MembershipRead */
    MembershipRead: {
      kind: components['schemas']['WorkspaceKind']
      role: components['schemas']['WorkspaceRole']
      /** Settings */
      settings: {
        [key: string]: unknown
      }
      /** Slug */
      slug: string | null
      status: components['schemas']['MembershipStatus']
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
      /** Workspace Name */
      workspace_name: string
    }
    /**
     * MembershipStatus
     * @enum {string}
     */
    MembershipStatus: 'invited' | 'active' | 'departed'
    /** OnboardingProfile */
    OnboardingProfile: {
      /** Full Name */
      full_name: string
      /**
       * Role Title
       * @default
       */
      role_title?: string
      /**
       * Timezone
       * @default UTC
       */
      timezone?: string
    }
    /**
     * OnboardingUpdate
     * @description One call per step so progress survives reloads.
     *
     *     Steps: 1 profile, 2 interests, 3 goals, 4 integrations, 5 done.
     */
    OnboardingUpdate: {
      goals?: components['schemas']['Goals'] | null
      /** Interests */
      interests?: components['schemas']['InterestIn'][] | null
      profile?: components['schemas']['OnboardingProfile'] | null
      /** Step */
      step: number
    }
    /** ProfileRead */
    ProfileRead: {
      /** Avatar Path */
      avatar_path: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Default Workspace Id */
      default_workspace_id: string | null
      /** Email */
      email: string
      /** Full Name */
      full_name: string
      /** Goals */
      goals: {
        [key: string]: unknown
      }
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Onboarding Completed At */
      onboarding_completed_at: string | null
      /** Onboarding Step */
      onboarding_step: number
      /** Role Title */
      role_title: string | null
      /** Timezone */
      timezone: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** WorkspaceCreate */
    WorkspaceCreate: {
      /** Name */
      name: string
      settings?: components['schemas']['WorkspaceSettings']
      /** Slug */
      slug?: string | null
    }
    /**
     * WorkspaceKind
     * @enum {string}
     */
    WorkspaceKind: 'personal' | 'organization'
    /** WorkspaceRead */
    WorkspaceRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['WorkspaceKind']
      my_role?: components['schemas']['WorkspaceRole'] | null
      /** Name */
      name: string
      /**
       * Owner User Id
       * Format: uuid
       */
      owner_user_id: string
      /** Plan */
      plan: string
      /** Settings */
      settings: {
        [key: string]: unknown
      }
      /** Slug */
      slug: string | null
    }
    /**
     * WorkspaceRole
     * @enum {string}
     */
    WorkspaceRole: 'viewer' | 'member' | 'manager' | 'admin' | 'owner'
    /** WorkspaceSettings */
    WorkspaceSettings: {
      /**
       * Ai Daily Token Budget
       * @default 500000
       */
      ai_daily_token_budget?: number
      /**
       * Auto Apply Low Risk Facts
       * @default false
       */
      auto_apply_low_risk_facts?: boolean
      /**
       * Default Cadence Days
       * @default 30
       */
      default_cadence_days?: number
      /**
       * Default Contact Visibility
       * @default team
       */
      default_contact_visibility?: string
      /**
       * Narrate Insights With Llm
       * @default false
       */
      narrate_insights_with_llm?: boolean
      /**
       * Require Mfa
       * @default false
       */
      require_mfa?: boolean
      /**
       * Retain Audio
       * @default false
       */
      retain_audio?: boolean
    }
    /** WorkspaceUpdate */
    WorkspaceUpdate: {
      /** Name */
      name?: string | null
      settings?: components['schemas']['WorkspaceSettings'] | null
      /** Slug */
      slug?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  invitations_peek: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationPeek']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_accept: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AcceptResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
    }
  }
  me_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_onboarding_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead'][]
        }
      }
    }
  }
  workspaces_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_list: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_revoke: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
        invitation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_list: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_leave: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_live: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  health_ready: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
