/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/analytics/distribution': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analytics Distribution */
    get: operations['analytics_distribution']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/interactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analytics Interactions */
    get: operations['analytics_interactions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analytics Summary */
    get: operations['analytics_summary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/team': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analytics Team */
    get: operations['analytics_team']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/top-contacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analytics Top Contacts */
    get: operations['analytics_top_contacts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Captures List */
    get: operations['captures_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/text': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Captures Create Text */
    post: operations['captures_create_text']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/voice/upload-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Captures Voice Upload Url */
    post: operations['captures_voice_upload_url']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/{capture_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Captures Get */
    get: operations['captures_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/{capture_id}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Captures Confirm */
    post: operations['captures_confirm']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/{capture_id}/discard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Captures Discard */
    post: operations['captures_discard']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/captures/{capture_id}/uploaded': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Captures Voice Uploaded */
    post: operations['captures_voice_uploaded']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/companies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Companies List */
    get: operations['companies_list']
    put?: never
    /** Companies Create */
    post: operations['companies_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/companies/{company_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Companies Get */
    get: operations['companies_get']
    put?: never
    post?: never
    /** Companies Delete */
    delete: operations['companies_delete']
    options?: never
    head?: never
    /** Companies Update */
    patch: operations['companies_update']
    trace?: never
  }
  '/api/v1/contacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Contacts List */
    get: operations['contacts_list']
    put?: never
    /** Contacts Create */
    post: operations['contacts_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Contacts Get */
    get: operations['contacts_get']
    put?: never
    post?: never
    /** Contacts Delete */
    delete: operations['contacts_delete']
    options?: never
    head?: never
    /** Contacts Update */
    patch: operations['contacts_update']
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/brief': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Brief Create */
    post: operations['brief_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/copy-to-personal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Contacts Copy To Personal */
    post: operations['contacts_copy_to_personal']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/facts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Facts List */
    get: operations['facts_list']
    put?: never
    /** Facts Create */
    post: operations['facts_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Profile Get */
    get: operations['profile_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/profile/regenerate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Profile Regenerate */
    post: operations['profile_regenerate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/scores': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Scores History */
    get: operations['scores_history']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/share': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Contacts Share */
    post: operations['contacts_share']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/contacts/{contact_id}/timeline': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Contacts Timeline */
    get: operations['contacts_timeline']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/facts/{fact_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Facts Delete */
    delete: operations['facts_delete']
    options?: never
    head?: never
    /** Facts Update */
    patch: operations['facts_update']
    trace?: never
  }
  '/api/v1/insights': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Insights List */
    get: operations['insights_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/insights/generate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Insights Generate Now */
    post: operations['insights_generate_now']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/insights/{insight_id}/act': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Insights Act */
    post: operations['insights_act']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/insights/{insight_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Insights Set Status */
    post: operations['insights_set_status']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/interactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Interactions List */
    get: operations['interactions_list']
    put?: never
    /** Interactions Create */
    post: operations['interactions_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/interactions/{interaction_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Interactions Delete */
    delete: operations['interactions_delete']
    options?: never
    head?: never
    /** Interactions Update */
    patch: operations['interactions_update']
    trace?: never
  }
  '/api/v1/invitations/{token}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Invitations Peek */
    get: operations['invitations_peek']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invitations/{token}/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Invitations Accept */
    post: operations['invitations_accept']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Jobs Get */
    get: operations['jobs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me Get */
    get: operations['me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Me Update */
    patch: operations['me_update']
    trace?: never
  }
  '/api/v1/me/onboarding': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Me Onboarding Update */
    patch: operations['me_onboarding_update']
    trace?: never
  }
  '/api/v1/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search Global */
    get: operations['search_global']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Workspaces List */
    get: operations['workspaces_list']
    put?: never
    /** Workspaces Create */
    post: operations['workspaces_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Workspaces Get */
    get: operations['workspaces_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Workspaces Update */
    patch: operations['workspaces_update']
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/invitations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Invitations List */
    get: operations['invitations_list']
    put?: never
    /** Invitations Create */
    post: operations['invitations_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/invitations/{invitation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Invitations Revoke */
    delete: operations['invitations_revoke']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Members List */
    get: operations['members_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Members Leave */
    delete: operations['members_leave']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/workspaces/{workspace_id}/members/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Members Update */
    patch: operations['members_update']
    trace?: never
  }
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Live */
    get: operations['health_live']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Ready */
    get: operations['health_ready']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AcceptResult */
    AcceptResult: {
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /**
     * AiStatus
     * @enum {string}
     */
    AiStatus: 'none' | 'pending' | 'processed' | 'failed' | 'skipped'
    /** AnalyticsSummary */
    AnalyticsSummary: {
      /** Active Count */
      active_count: number
      /** Avg Gravity */
      avg_gravity: number
      /** Avg Gravity Delta */
      avg_gravity_delta: number
      /** Contact Count */
      contact_count: number
      /** Contact Count Delta */
      contact_count_delta: number
      /** Due Count */
      due_count: number
      /** Engagement Rate */
      engagement_rate: number
      /** Open Opportunity Count */
      open_opportunity_count: number
      /** Pipeline Delta Pct */
      pipeline_delta_pct: number
      /** Pipeline Value Cents */
      pipeline_value_cents: number
      /** Range */
      range: string
      /**
       * Scope
       * @enum {string}
       */
      scope: 'me' | 'team'
    }
    /**
     * Band
     * @enum {string}
     */
    Band: 'strong' | 'steady' | 'weak' | 'drifting'
    /** BandCount */
    BandCount: {
      /** Band */
      band: string
      /** Count */
      count: number
    }
    /** CaptureConfirm */
    CaptureConfirm: {
      /**
       * Contact Id
       * Format: uuid
       */
      contact_id: string
      /** Create Contacts For */
      create_contacts_for?: components['schemas']['MentionedPerson'][]
      /** Edges */
      edges?: components['schemas']['ExtractedEdge'][]
      /** Facts */
      facts?: components['schemas']['ExtractedFact'][]
      interaction: components['schemas']['ExtractedInteraction']
      /** Tasks */
      tasks?: components['schemas']['ExtractedTask'][]
    }
    /** CaptureExtraction */
    CaptureExtraction: {
      contact_match?: components['schemas']['ContactMatch'] | null
      /** Edges */
      edges?: components['schemas']['ExtractedEdge'][]
      /** Facts */
      facts?: components['schemas']['ExtractedFact'][]
      interaction: components['schemas']['ExtractedInteraction']
      /** Mentioned Companies */
      mentioned_companies?: string[]
      /** Mentioned People */
      mentioned_people?: components['schemas']['MentionedPerson'][]
      /** Needs Review */
      needs_review?: string[]
      /** Tasks */
      tasks?: components['schemas']['ExtractedTask'][]
    }
    /** CaptureRead */
    CaptureRead: {
      /** Contact Id */
      contact_id: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Duration Seconds */
      duration_seconds: number | null
      /** Error */
      error: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Interaction Id */
      interaction_id: string | null
      /** Kind */
      kind: string
      proposal: components['schemas']['CaptureExtraction'] | null
      /** Provenance */
      provenance: {
        [key: string]: unknown
      }
      /** Raw Text */
      raw_text: string | null
      status: components['schemas']['CaptureStatus']
      /** Transcript */
      transcript: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /**
     * CaptureStatus
     * @enum {string}
     */
    CaptureStatus:
      | 'uploaded'
      | 'transcribing'
      | 'transcribed'
      | 'extracting'
      | 'proposed'
      | 'confirmed'
      | 'discarded'
      | 'failed'
    /** CaptureTextCreate */
    CaptureTextCreate: {
      /** Contact Id */
      contact_id?: string | null
      /** Idempotency Key */
      idempotency_key: string
      /** Text */
      text: string
    }
    /** CompanyCreate */
    CompanyCreate: {
      /** Domain */
      domain?: string | null
      /** Industry */
      industry?: string | null
      /** Name */
      name: string
      /** Notes */
      notes?: string | null
      /** @default other */
      type?: components['schemas']['CompanyType']
    }
    /** CompanyHit */
    CompanyHit: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Industry */
      industry: string | null
      /** Name */
      name: string
    }
    /** CompanyRead */
    CompanyRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Created By
       * Format: uuid
       */
      created_by: string
      /** Domain */
      domain: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Industry */
      industry: string | null
      /** Name */
      name: string
      /** Notes */
      notes: string | null
      type: components['schemas']['CompanyType']
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /** CompanySummary */
    CompanySummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Industry */
      industry?: string | null
      /** Name */
      name: string
    }
    /**
     * CompanyType
     * @enum {string}
     */
    CompanyType: 'client' | 'partner' | 'vendor' | 'government' | 'prospect' | 'other'
    /** CompanyUpdate */
    CompanyUpdate: {
      /** Domain */
      domain?: string | null
      /** Industry */
      industry?: string | null
      /** Name */
      name?: string | null
      /** Notes */
      notes?: string | null
      type?: components['schemas']['CompanyType'] | null
    }
    /** ConfirmResult */
    ConfirmResult: {
      contact: components['schemas']['ContactRead']
      /** Created Contact Ids */
      created_contact_ids: string[]
      /** Fact Ids */
      fact_ids: string[]
      interaction: components['schemas']['InteractionRead']
      /** Task Ids */
      task_ids: string[]
    }
    /** ContactCreate */
    ContactCreate: {
      /**
       * Cadence Days
       * @default 30
       */
      cadence_days?: number
      /** Company Id */
      company_id?: string | null
      /** Company Name */
      company_name?: string | null
      /** Emails */
      emails?: string[]
      /** First Name */
      first_name: string
      /** Honorific */
      honorific?: string | null
      /**
       * Last Name
       * @default
       */
      last_name?: string
      /** Location */
      location?: string | null
      /** Phones */
      phones?: string[]
      /** @default other */
      relationship_type?: components['schemas']['RelationshipType']
      /** Tags */
      tags?: string[]
      /** Title */
      title?: string | null
      visibility?: components['schemas']['ContactVisibility'] | null
    }
    /** ContactHit */
    ContactHit: {
      /** Company Name */
      company_name: string | null
      /** Display Name */
      display_name: string
      /** Gravity Score */
      gravity_score: number
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string | null
    }
    /** ContactMatch */
    ContactMatch: {
      /** Confidence */
      confidence: number
      /** Contact Id */
      contact_id: string
      /** Display Name */
      display_name: string
    }
    /** ContactProfileRead */
    ContactProfileRead: {
      /** Common Ground */
      common_ground: string[]
      /** Communication Style */
      communication_style: string | null
      /** Generated At */
      generated_at: string | null
      /** Model */
      model: string | null
      /** Prompt Version */
      prompt_version: string | null
      /** Remember */
      remember: string[]
      /** Risks */
      risks: string[]
      /** Stale */
      stale: boolean
      /** Summary */
      summary: string
      /** Talking Points */
      talking_points: string[]
    }
    /** ContactRead */
    ContactRead: {
      band: components['schemas']['Band']
      /** Cadence Days */
      cadence_days: number
      company: components['schemas']['CompanySummary'] | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Display Name */
      display_name: string
      /** Emails */
      emails: string[]
      /** First Name */
      first_name: string
      /** Gravity Score */
      gravity_score: number
      /** Honorific */
      honorific: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      last_interaction: components['schemas']['InteractionSummary'] | null
      /** Last Name */
      last_name: string
      /** Location */
      location: string | null
      /** Next Due At */
      next_due_at: string | null
      /** Open Opportunity Value Cents */
      open_opportunity_value_cents: number
      /** Open Task Count */
      open_task_count: number
      /** Origin Contact Id */
      origin_contact_id: string | null
      /**
       * Owner User Id
       * Format: uuid
       */
      owner_user_id: string
      /** Phones */
      phones: string[]
      profile?: components['schemas']['ContactProfileRead'] | null
      relationship_type: components['schemas']['RelationshipType']
      /** Score Delta 30D */
      score_delta_30d: number | null
      status: components['schemas']['ContactStatus']
      /** Tags */
      tags: string[]
      /** Title */
      title: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      visibility: components['schemas']['ContactVisibility']
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /**
     * ContactStatus
     * @enum {string}
     */
    ContactStatus: 'active' | 'follow_up' | 'needs_attention' | 'drifting' | 'archived'
    /** ContactUpdate */
    ContactUpdate: {
      /** Cadence Days */
      cadence_days?: number | null
      /** Company Id */
      company_id?: string | null
      /** Company Name */
      company_name?: string | null
      /** Emails */
      emails?: string[] | null
      /** First Name */
      first_name?: string | null
      /** Honorific */
      honorific?: string | null
      /** Last Name */
      last_name?: string | null
      /** Location */
      location?: string | null
      /** Phones */
      phones?: string[] | null
      relationship_type?: components['schemas']['RelationshipType'] | null
      status?: components['schemas']['ContactStatus'] | null
      /** Tags */
      tags?: string[] | null
      /** Title */
      title?: string | null
      visibility?: components['schemas']['ContactVisibility'] | null
    }
    /**
     * ContactVisibility
     * @enum {string}
     */
    ContactVisibility: 'private' | 'team'
    /** ExtractedEdge */
    ExtractedEdge: {
      /**
       * Kind
       * @default knows
       * @enum {string}
       */
      kind?: 'knows' | 'reports_to' | 'works_with' | 'introduced_by' | 'former_colleague' | 'other'
      /** Person A */
      person_a: string
      /** Person B */
      person_b: string
    }
    /** ExtractedFact */
    ExtractedFact: {
      category: components['schemas']['FactCategory']
      /**
       * Confidence
       * @default 0.8
       */
      confidence?: number
      /** Content */
      content: string
      /**
       * Supersedes
       * @description Existing fact this one contradicts, verbatim
       */
      supersedes?: string | null
    }
    /** ExtractedInteraction */
    ExtractedInteraction: {
      /**
       * Body
       * @default
       */
      body?: string
      /** @default mutual */
      direction?: components['schemas']['InteractionDirection']
      /** @default note */
      kind?: components['schemas']['InteractionKind']
      /** Occurred At */
      occurred_at?: string | null
      /** @default neutral */
      sentiment?: components['schemas']['SentimentLabel']
      /**
       * Sentiment Score
       * @default 0
       */
      sentiment_score?: number
      /**
       * Subject
       * @default
       */
      subject?: string
      /**
       * Summary
       * @default
       */
      summary?: string
    }
    /** ExtractedTask */
    ExtractedTask: {
      /**
       * Contact Ref
       * @description Name of the person the task concerns, if not the main contact
       */
      contact_ref?: string | null
      /** Due At */
      due_at?: string | null
      /**
       * Priority
       * @default 2
       */
      priority?: number
      /** Title */
      title: string
    }
    /**
     * FactCategory
     * @enum {string}
     */
    FactCategory:
      | 'preference'
      | 'dislike'
      | 'interest'
      | 'personal'
      | 'professional'
      | 'communication_style'
      | 'ambition'
      | 'family'
      | 'risk'
      | 'other'
    /** FactCreate */
    FactCreate: {
      category: components['schemas']['FactCategory']
      /**
       * Confidence
       * @default 1
       */
      confidence?: number
      /** Content */
      content: string
      /** @default manual */
      source?: components['schemas']['FactSource']
    }
    /** FactRead */
    FactRead: {
      category: components['schemas']['FactCategory']
      /** Confidence */
      confidence: number
      /**
       * Contact Id
       * Format: uuid
       */
      contact_id: string
      /** Content */
      content: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Created By
       * Format: uuid
       */
      created_by: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Is Active */
      is_active: boolean
      source: components['schemas']['FactSource']
      /** Source Interaction Id */
      source_interaction_id: string | null
      /** Superseded By */
      superseded_by: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * FactSource
     * @enum {string}
     */
    FactSource: 'manual' | 'note' | 'voice' | 'email' | 'calendar' | 'crm' | 'ai'
    /** FactUpdate */
    FactUpdate: {
      category?: components['schemas']['FactCategory'] | null
      /** Confidence */
      confidence?: number | null
      /** Content */
      content?: string | null
    }
    /** Goals */
    Goals: {
      /**
       * Close Deals
       * @default false
       */
      close_deals?: boolean
      /**
       * Expand Network
       * @default false
       */
      expand_network?: boolean
      /**
       * Free Text
       * @default
       */
      free_text?: string
      /**
       * Strengthen
       * @default false
       */
      strengthen?: boolean
      /**
       * Track Roi
       * @default false
       */
      track_roi?: boolean
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InsightActResult */
    InsightActResult: {
      insight: components['schemas']['InsightRead']
      /** Navigate To */
      navigate_to?: string | null
      /** Task Id */
      task_id?: string | null
    }
    /**
     * InsightKind
     * @enum {string}
     */
    InsightKind:
      | 'follow_up'
      | 'at_risk'
      | 'opportunity_signal'
      | 'introduction_path'
      | 'trend'
      | 'briefing'
      | 'common_ground'
    /** InsightRead */
    InsightRead: {
      /** Body */
      body: string
      /** Company Id */
      company_id: string | null
      /** Company Name */
      company_name: string | null
      /** Contact Id */
      contact_id: string | null
      /** Contact Name */
      contact_name: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Evidence */
      evidence: {
        [key: string]: unknown
      }
      /** Expires At */
      expires_at: string | null
      /** Generated By */
      generated_by: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['InsightKind']
      severity: components['schemas']['InsightSeverity']
      status: components['schemas']['InsightStatus']
      /** Suggested Action */
      suggested_action: {
        [key: string]: unknown
      } | null
      /** Title */
      title: string
      /** User Id */
      user_id: string | null
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /**
     * InsightSeverity
     * @enum {string}
     */
    InsightSeverity: 'info' | 'notice' | 'warning'
    /**
     * InsightStatus
     * @enum {string}
     */
    InsightStatus: 'new' | 'seen' | 'acted' | 'dismissed' | 'expired'
    /** InsightStatusUpdate */
    InsightStatusUpdate: {
      /**
       * Status
       * @enum {string}
       */
      status: 'seen' | 'acted' | 'dismissed'
    }
    /** InteractionCreate */
    InteractionCreate: {
      /**
       * Body
       * @default
       */
      body?: string
      /**
       * Contact Id
       * Format: uuid
       */
      contact_id: string
      /** @default mutual */
      direction?: components['schemas']['InteractionDirection']
      /**
       * Extract
       * @default false
       */
      extract?: boolean
      /** @default note */
      kind?: components['schemas']['InteractionKind']
      /** Occurred At */
      occurred_at?: string | null
      sentiment?: components['schemas']['SentimentLabel'] | null
      /** Sentiment Score */
      sentiment_score?: number | null
      /** Subject */
      subject?: string | null
      /** Summary */
      summary?: string | null
    }
    /**
     * InteractionDirection
     * @enum {string}
     */
    InteractionDirection: 'inbound' | 'outbound' | 'mutual'
    /** InteractionHit */
    InteractionHit: {
      /** Contact Id */
      contact_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Occurred At */
      occurred_at: string
      /** Snippet */
      snippet: string
      /** Subject */
      subject: string | null
    }
    /**
     * InteractionKind
     * @enum {string}
     */
    InteractionKind:
      | 'note'
      | 'meeting'
      | 'call'
      | 'email'
      | 'message'
      | 'event'
      | 'introduction'
      | 'gift'
      | 'other'
    /** InteractionRead */
    InteractionRead: {
      /** Ai Extraction */
      ai_extraction: {
        [key: string]: unknown
      } | null
      ai_status: components['schemas']['AiStatus']
      /** Body */
      body: string
      /** Contact Id */
      contact_id: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      direction: components['schemas']['InteractionDirection']
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['InteractionKind']
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string
      sentiment: components['schemas']['SentimentLabel'] | null
      /** Sentiment Score */
      sentiment_score: number | null
      source: components['schemas']['InteractionSource']
      /** Subject */
      subject: string | null
      /** Summary */
      summary: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /**
     * InteractionSource
     * @enum {string}
     */
    InteractionSource:
      | 'manual'
      | 'voice'
      | 'gmail'
      | 'outlook'
      | 'google_calendar'
      | 'ms_calendar'
      | 'crm'
      | 'import'
    /** InteractionSummary */
    InteractionSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['InteractionKind']
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string
      /** Subject */
      subject: string | null
      /** Summary */
      summary: string | null
    }
    /** InteractionUpdate */
    InteractionUpdate: {
      /** Body */
      body?: string | null
      direction?: components['schemas']['InteractionDirection'] | null
      kind?: components['schemas']['InteractionKind'] | null
      /** Occurred At */
      occurred_at?: string | null
      sentiment?: components['schemas']['SentimentLabel'] | null
      /** Sentiment Score */
      sentiment_score?: number | null
      /** Subject */
      subject?: string | null
      /** Summary */
      summary?: string | null
    }
    /** InterestIn */
    InterestIn: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'professional' | 'personal'
      /** Value */
      value: string
    }
    /** InterestRead */
    InterestRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Value */
      value: string
    }
    /** InvitationCreate */
    InvitationCreate: {
      /** Email */
      email: string
      /** @default member */
      role?: components['schemas']['WorkspaceRole']
    }
    /** InvitationPeek */
    InvitationPeek: {
      /** Accepted */
      accepted: boolean
      /** Email */
      email: string
      /** Expired */
      expired: boolean
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Inviter Name */
      inviter_name: string
      role: components['schemas']['WorkspaceRole']
      /** Workspace Name */
      workspace_name: string
    }
    /** InvitationRead */
    InvitationRead: {
      /** Accepted At */
      accepted_at: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Email */
      email: string
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Invited By
       * Format: uuid
       */
      invited_by: string
      role: components['schemas']['WorkspaceRole']
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
    }
    /** JobAccepted */
    JobAccepted: {
      /** Deduplicated */
      deduplicated: boolean
      /** Job Id */
      job_id: string | null
    }
    /** JobRead */
    JobRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Finished At */
      finished_at: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Last Error */
      last_error: string | null
      /** Result */
      result: {
        [key: string]: unknown
      } | null
      /** Status */
      status: string
    }
    /** MeRead */
    MeRead: {
      /** Interests */
      interests: components['schemas']['InterestRead'][]
      /** Memberships */
      memberships: components['schemas']['MembershipRead'][]
      profile: components['schemas']['ProfileRead']
    }
    /** MeUpdate */
    MeUpdate: {
      /** Default Workspace Id */
      default_workspace_id?: string | null
      /** Full Name */
      full_name?: string | null
      goals?: components['schemas']['Goals'] | null
      /** Interests */
      interests?: components['schemas']['InterestIn'][] | null
      /** Role Title */
      role_title?: string | null
      /** Timezone */
      timezone?: string | null
    }
    /** MemberMetrics */
    MemberMetrics: {
      /** Avg Gravity */
      avg_gravity: number
      /** Contact Count */
      contact_count: number
      /** Full Name */
      full_name: string
      /** Interactions In Range */
      interactions_in_range: number
      /** Overdue Tasks */
      overdue_tasks: number
      /** Pipeline Value Cents */
      pipeline_value_cents: number
      /** Role */
      role: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /** MemberRead */
    MemberRead: {
      /** Avatar Path */
      avatar_path: string | null
      /** Departed At */
      departed_at: string | null
      /** Email */
      email: string
      /** Full Name */
      full_name: string
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
      role: components['schemas']['WorkspaceRole']
      /** Role Title */
      role_title: string | null
      status: components['schemas']['MembershipStatus']
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /** MemberUpdate */
    MemberUpdate: {
      role?: components['schemas']['WorkspaceRole'] | null
      status?: components['schemas']['MembershipStatus'] | null
    }
    /** MembershipRead */
    MembershipRead: {
      kind: components['schemas']['WorkspaceKind']
      role: components['schemas']['WorkspaceRole']
      /** Settings */
      settings: {
        [key: string]: unknown
      }
      /** Slug */
      slug: string | null
      status: components['schemas']['MembershipStatus']
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string
      /** Workspace Name */
      workspace_name: string
    }
    /**
     * MembershipStatus
     * @enum {string}
     */
    MembershipStatus: 'invited' | 'active' | 'departed'
    /** MentionedPerson */
    MentionedPerson: {
      /** Company */
      company?: string | null
      /** Name */
      name: string
      /** Relationship Hint */
      relationship_hint?: string | null
      /** Title */
      title?: string | null
    }
    /** OnboardingProfile */
    OnboardingProfile: {
      /** Full Name */
      full_name: string
      /**
       * Role Title
       * @default
       */
      role_title?: string
      /**
       * Timezone
       * @default UTC
       */
      timezone?: string
    }
    /**
     * OnboardingUpdate
     * @description One call per step so progress survives reloads.
     *
     *     Steps: 1 profile, 2 interests, 3 goals, 4 integrations, 5 done.
     */
    OnboardingUpdate: {
      goals?: components['schemas']['Goals'] | null
      /** Interests */
      interests?: components['schemas']['InterestIn'][] | null
      profile?: components['schemas']['OnboardingProfile'] | null
      /** Step */
      step: number
    }
    /** Page[CompanyRead] */
    Page_CompanyRead_: {
      /** Items */
      items: components['schemas']['CompanyRead'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** Page[ContactRead] */
    Page_ContactRead_: {
      /** Items */
      items: components['schemas']['ContactRead'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** Page[InteractionRead] */
    Page_InteractionRead_: {
      /** Items */
      items: components['schemas']['InteractionRead'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** Page[TimelineEntry] */
    Page_TimelineEntry_: {
      /** Items */
      items: components['schemas']['TimelineEntry'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** ProfileRead */
    ProfileRead: {
      /** Avatar Path */
      avatar_path: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Default Workspace Id */
      default_workspace_id: string | null
      /** Email */
      email: string
      /** Full Name */
      full_name: string
      /** Goals */
      goals: {
        [key: string]: unknown
      }
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Onboarding Completed At */
      onboarding_completed_at: string | null
      /** Onboarding Step */
      onboarding_step: number
      /** Role Title */
      role_title: string | null
      /** Timezone */
      timezone: string
    }
    /**
     * RelationshipType
     * @enum {string}
     */
    RelationshipType: 'client' | 'partner' | 'vendor' | 'colleague' | 'government' | 'other'
    /** ScorePoint */
    ScorePoint: {
      /** Band */
      band: string
      /** Score */
      score: number
      /** Scored On */
      scored_on: string
    }
    /** SearchResult */
    SearchResult: {
      /** Companies */
      companies: components['schemas']['CompanyHit'][]
      /** Contacts */
      contacts: components['schemas']['ContactHit'][]
      /** Interactions */
      interactions: components['schemas']['InteractionHit'][]
    }
    /**
     * SentimentLabel
     * @enum {string}
     */
    SentimentLabel: 'positive' | 'neutral' | 'negative' | 'mixed'
    /** SeriesPoint */
    SeriesPoint: {
      /** Count */
      count: number
      /** Kind */
      kind: string
      /** Period */
      period: string
    }
    /** ShareRequest */
    ShareRequest: {
      /**
       * Target Workspace Id
       * Format: uuid
       */
      target_workspace_id: string
    }
    /** TimelineEntry */
    TimelineEntry: {
      /** Body */
      body: string
      /**
       * Entry Type
       * @enum {string}
       */
      entry_type: 'interaction' | 'task' | 'score'
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Kind */
      kind: string
      /** Meta */
      meta: {
        [key: string]: unknown
      }
      /** Title */
      title: string
      /**
       * Ts
       * Format: date-time
       */
      ts: string
    }
    /** TopContact */
    TopContact: {
      /** Band */
      band: string
      /** Company Name */
      company_name: string | null
      /** Deal Value Cents */
      deal_value_cents: number
      /** Display Name */
      display_name: string
      /** Gravity Score */
      gravity_score: number
      /** Honorific */
      honorific: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Last Interaction At */
      last_interaction_at: string | null
      /** Status */
      status: string
    }
    /** UploadedRequest */
    UploadedRequest: {
      /** Duration Seconds */
      duration_seconds?: number | null
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** VoiceUploadRequest */
    VoiceUploadRequest: {
      /** Contact Id */
      contact_id?: string | null
      /**
       * Content Type
       * @enum {string}
       */
      content_type: 'audio/webm' | 'audio/mp4' | 'audio/mpeg' | 'audio/wav'
      /** Idempotency Key */
      idempotency_key: string
      /** Size Bytes */
      size_bytes: number
    }
    /** VoiceUploadResponse */
    VoiceUploadResponse: {
      /**
       * Capture Id
       * Format: uuid
       */
      capture_id: string
      /** Headers */
      headers: {
        [key: string]: string
      }
      /** Storage Path */
      storage_path: string
      /** Token */
      token: string
      /** Upload Url */
      upload_url: string
    }
    /** WorkspaceCreate */
    WorkspaceCreate: {
      /** Name */
      name: string
      settings?: components['schemas']['WorkspaceSettings']
      /** Slug */
      slug?: string | null
    }
    /**
     * WorkspaceKind
     * @enum {string}
     */
    WorkspaceKind: 'personal' | 'organization'
    /** WorkspaceRead */
    WorkspaceRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['WorkspaceKind']
      my_role?: components['schemas']['WorkspaceRole'] | null
      /** Name */
      name: string
      /**
       * Owner User Id
       * Format: uuid
       */
      owner_user_id: string
      /** Plan */
      plan: string
      /** Settings */
      settings: {
        [key: string]: unknown
      }
      /** Slug */
      slug: string | null
    }
    /**
     * WorkspaceRole
     * @enum {string}
     */
    WorkspaceRole: 'viewer' | 'member' | 'manager' | 'admin' | 'owner'
    /** WorkspaceSettings */
    WorkspaceSettings: {
      /**
       * Ai Daily Token Budget
       * @default 500000
       */
      ai_daily_token_budget?: number
      /**
       * Auto Apply Low Risk Facts
       * @default false
       */
      auto_apply_low_risk_facts?: boolean
      /**
       * Default Cadence Days
       * @default 30
       */
      default_cadence_days?: number
      /**
       * Default Contact Visibility
       * @default team
       */
      default_contact_visibility?: string
      /**
       * Narrate Insights With Llm
       * @default false
       */
      narrate_insights_with_llm?: boolean
      /**
       * Require Mfa
       * @default false
       */
      require_mfa?: boolean
      /**
       * Retain Audio
       * @default false
       */
      retain_audio?: boolean
    }
    /** WorkspaceUpdate */
    WorkspaceUpdate: {
      /** Name */
      name?: string | null
      settings?: components['schemas']['WorkspaceSettings'] | null
      /** Slug */
      slug?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  analytics_distribution: {
    parameters: {
      query?: {
        scope?: 'me' | 'team'
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BandCount'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  analytics_interactions: {
    parameters: {
      query?: {
        range?: 'today' | 'week' | 'month' | 'quarter' | 'year'
        scope?: 'me' | 'team'
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SeriesPoint'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  analytics_summary: {
    parameters: {
      query?: {
        range?: 'today' | 'week' | 'month' | 'quarter' | 'year'
        scope?: 'me' | 'team'
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnalyticsSummary']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  analytics_team: {
    parameters: {
      query?: {
        range?: 'today' | 'week' | 'month' | 'quarter' | 'year'
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberMetrics'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  analytics_top_contacts: {
    parameters: {
      query?: {
        scope?: 'me' | 'team'
        q?: string | null
        limit?: number
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TopContact'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_list: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaptureRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_create_text: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CaptureTextCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaptureRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_voice_upload_url: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VoiceUploadRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VoiceUploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_get: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        capture_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaptureRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_confirm: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        capture_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CaptureConfirm']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfirmResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_discard: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        capture_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaptureRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  captures_voice_uploaded: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        capture_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UploadedRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaptureRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  companies_list: {
    parameters: {
      query?: {
        q?: string | null
        type?: string | null
        industry?: string | null
        limit?: number
        cursor?: string | null
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_CompanyRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  companies_create: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompanyCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompanyRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  companies_get: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompanyRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  companies_delete: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  companies_update: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        company_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompanyUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompanyRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_list: {
    parameters: {
      query?: {
        q?: string | null
        status?: string | null
        band?: string | null
        company_id?: string | null
        relationship_type?: string | null
        tag?: string | null
        owner?: string | null
        sort?: 'updated' | 'gravity' | 'last_interaction' | 'name' | 'next_due'
        limit?: number
        cursor?: string | null
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ContactRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_create: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ContactCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_get: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_delete: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_update: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ContactUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  brief_create: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_copy_to_personal: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  facts_list: {
    parameters: {
      query?: {
        include_inactive?: boolean
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FactRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  facts_create: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FactCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  profile_get: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactProfileRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  profile_regenerate: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  scores_history: {
    parameters: {
      query?: {
        range?: string
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScorePoint'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_share: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShareRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  contacts_timeline: {
    parameters: {
      query?: {
        kinds?: string[] | null
        limit?: number
        cursor?: string | null
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        contact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_TimelineEntry_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  facts_delete: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        fact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  facts_update: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        fact_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FactUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FactRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  insights_list: {
    parameters: {
      query?: {
        status?: string | null
        kind?: string | null
        contact_id?: string | null
        scope?: string
        limit?: number
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InsightRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  insights_generate_now: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  insights_act: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        insight_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InsightActResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  insights_set_status: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        insight_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InsightStatusUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InsightRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  interactions_list: {
    parameters: {
      query?: {
        contact_id?: string | null
        kind?: string | null
        since?: string | null
        until?: string | null
        limit?: number
        cursor?: string | null
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_InteractionRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  interactions_create: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InteractionCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InteractionRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  interactions_delete: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        interaction_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  interactions_update: {
    parameters: {
      query?: never
      header?: {
        'x-workspace-id'?: string | null
      }
      path: {
        interaction_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InteractionUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InteractionRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_peek: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationPeek']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_accept: {
    parameters: {
      query?: never
      header?: never
      path: {
        token: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AcceptResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  jobs_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
    }
  }
  me_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_onboarding_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_global: {
    parameters: {
      query: {
        q: string
      }
      header?: {
        'x-workspace-id'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead'][]
        }
      }
    }
  }
  workspaces_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspaces_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_list: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvitationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  invitations_revoke: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
        invitation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_list: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_leave: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  members_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_live: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  health_ready: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
